// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstore.proto

package petstore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_OrderStatusUnknown   OrderStatus = 0
	OrderStatus_OrderStatusPlaced    OrderStatus = 1
	OrderStatus_OrderStatusApproved  OrderStatus = 2
	OrderStatus_OrderStatusDelivered OrderStatus = 3
)

var OrderStatus_name = map[int32]string{
	0: "OrderStatusUnknown",
	1: "OrderStatusPlaced",
	2: "OrderStatusApproved",
	3: "OrderStatusDelivered",
}
var OrderStatus_value = map[string]int32{
	"OrderStatusUnknown":   0,
	"OrderStatusPlaced":    1,
	"OrderStatusApproved":  2,
	"OrderStatusDelivered": 3,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{0}
}

type PetStatus int32

const (
	PetStatus_PetStatusUnknown   PetStatus = 0
	PetStatus_PetStatusAvailable PetStatus = 1
	PetStatus_PetStatusPending   PetStatus = 2
	PetStatus_PetStatusSold      PetStatus = 3
)

var PetStatus_name = map[int32]string{
	0: "PetStatusUnknown",
	1: "PetStatusAvailable",
	2: "PetStatusPending",
	3: "PetStatusSold",
}
var PetStatus_value = map[string]int32{
	"PetStatusUnknown":   0,
	"PetStatusAvailable": 1,
	"PetStatusPending":   2,
	"PetStatusSold":      3,
}

func (x PetStatus) String() string {
	return proto.EnumName(PetStatus_name, int32(x))
}
func (PetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{1}
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{0}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{1}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Order struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PetId                int64       `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`
	Quantity             int32       `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status               OrderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=petstore.OrderStatus" json:"status,omitempty"`
	Complete             bool        `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{3}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetPetId() int64 {
	if m != nil {
		return m.PetId
	}
	return 0
}

func (m *Order) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_OrderStatusUnknown
}

func (m *Order) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type Pet struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrls            []string  `protobuf:"bytes,4,rep,name=photoUrls,proto3" json:"photoUrls,omitempty"`
	Tags                 []*Tag    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status               PetStatus `protobuf:"varint,6,opt,name=status,proto3,enum=petstore.PetStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Pet) Reset()         { *m = Pet{} }
func (m *Pet) String() string { return proto.CompactTextString(m) }
func (*Pet) ProtoMessage()    {}
func (*Pet) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{4}
}
func (m *Pet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pet.Unmarshal(m, b)
}
func (m *Pet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pet.Marshal(b, m, deterministic)
}
func (dst *Pet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pet.Merge(dst, src)
}
func (m *Pet) XXX_Size() int {
	return xxx_messageInfo_Pet.Size(m)
}
func (m *Pet) XXX_DiscardUnknown() {
	xxx_messageInfo_Pet.DiscardUnknown(m)
}

var xxx_messageInfo_Pet proto.InternalMessageInfo

func (m *Pet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pet) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Pet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pet) GetPhotoUrls() []string {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

func (m *Pet) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Pet) GetStatus() PetStatus {
	if m != nil {
		return m.Status
	}
	return PetStatus_PetStatusUnknown
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_c13949c920bef8e4, []int{5}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Tag)(nil), "petstore.Tag")
	proto.RegisterType((*Category)(nil), "petstore.Category")
	proto.RegisterType((*User)(nil), "petstore.User")
	proto.RegisterType((*Order)(nil), "petstore.Order")
	proto.RegisterType((*Pet)(nil), "petstore.Pet")
	proto.RegisterType((*Empty)(nil), "petstore.Empty")
	proto.RegisterEnum("petstore.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("petstore.PetStatus", PetStatus_name, PetStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetstoreServiceClient is the client API for PetstoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetstoreServiceClient interface {
	CreatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Empty, error)
}

type petstoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPetstoreServiceClient(cc *grpc.ClientConn) PetstoreServiceClient {
	return &petstoreServiceClient{cc}
}

func (c *petstoreServiceClient) CreatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/petstore.PetstoreService/CreatePet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetstoreServiceServer is the server API for PetstoreService service.
type PetstoreServiceServer interface {
	CreatePet(context.Context, *Pet) (*Empty, error)
}

func RegisterPetstoreServiceServer(s *grpc.Server, srv PetstoreServiceServer) {
	s.RegisterService(&_PetstoreService_serviceDesc, srv)
}

func _PetstoreService_CreatePet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetstoreServiceServer).CreatePet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/petstore.PetstoreService/CreatePet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetstoreServiceServer).CreatePet(ctx, req.(*Pet))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetstoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "petstore.PetstoreService",
	HandlerType: (*PetstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePet",
			Handler:    _PetstoreService_CreatePet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "petstore.proto",
}

func init() { proto.RegisterFile("petstore.proto", fileDescriptor_petstore_c13949c920bef8e4) }

var fileDescriptor_petstore_c13949c920bef8e4 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x92, 0xd2, 0x4e,
	0x14, 0xfe, 0x25, 0x21, 0x0c, 0x3c, 0x7e, 0x30, 0x99, 0x1e, 0x66, 0x4c, 0x51, 0xb3, 0xc0, 0xac,
	0x10, 0x4b, 0x28, 0x71, 0xe7, 0xc6, 0x9a, 0x1a, 0x5d, 0xb8, 0x51, 0x2a, 0x0c, 0x07, 0x68, 0xc8,
	0x33, 0xd3, 0x65, 0xe8, 0x8e, 0x9d, 0x06, 0x8b, 0xad, 0x57, 0xd0, 0x85, 0x37, 0xf2, 0x00, 0x5e,
	0xc1, 0x83, 0x58, 0xdd, 0x81, 0x4e, 0xa8, 0xd9, 0xb8, 0xe3, 0xfb, 0xd3, 0x79, 0xdf, 0xfb, 0x5e,
	0x01, 0xbd, 0x1c, 0x55, 0xa1, 0x84, 0xc4, 0x49, 0x2e, 0x85, 0x12, 0xa4, 0x75, 0xc4, 0x83, 0x9b,
	0x54, 0x88, 0x34, 0xc3, 0x29, 0xcd, 0xd9, 0x94, 0x72, 0x2e, 0x14, 0x55, 0x4c, 0xf0, 0xa2, 0xf4,
	0x45, 0xcf, 0xc0, 0xbb, 0xa7, 0x29, 0xe9, 0x81, 0xcb, 0x92, 0xd0, 0x19, 0x3a, 0x23, 0x2f, 0x76,
	0x59, 0x42, 0x08, 0x34, 0x38, 0xdd, 0x60, 0xe8, 0x0e, 0x9d, 0x51, 0x3b, 0x36, 0xbf, 0xa3, 0x09,
	0xb4, 0xee, 0xa8, 0xc2, 0x54, 0xc8, 0xfd, 0x3f, 0xf9, 0x7f, 0x3a, 0xd0, 0x58, 0x16, 0x28, 0x1f,
	0x99, 0x07, 0xd0, 0xda, 0x16, 0x28, 0x6b, 0x0f, 0x2c, 0x26, 0x37, 0xd0, 0xfe, 0xc4, 0x64, 0xa1,
	0x3e, 0x68, 0xd1, 0x33, 0x62, 0x45, 0xe8, 0x97, 0x19, 0x3d, 0x88, 0x8d, 0xf2, 0xe5, 0x11, 0x93,
	0x3e, 0xf8, 0xb8, 0xa1, 0x2c, 0x0b, 0x7d, 0x23, 0x94, 0x40, 0xb3, 0xf9, 0x83, 0xe0, 0x18, 0x36,
	0x4b, 0xd6, 0x80, 0xe8, 0x87, 0x03, 0xfe, 0x47, 0x99, 0x9c, 0x64, 0x6b, 0x98, 0x6c, 0xda, 0x8f,
	0xea, 0x7d, 0x62, 0x82, 0x79, 0x71, 0x09, 0xf4, 0xdc, 0x2f, 0x5b, 0xca, 0x15, 0x53, 0x7b, 0x13,
	0xca, 0x8f, 0x2d, 0x26, 0x2f, 0xa0, 0x59, 0x28, 0xaa, 0xb6, 0x85, 0x49, 0xd4, 0x9b, 0x5d, 0x4d,
	0xec, 0x29, 0xcc, 0x88, 0x85, 0x11, 0xe3, 0x83, 0x49, 0x7f, 0x6a, 0x2d, 0x36, 0x79, 0x86, 0x0a,
	0x4d, 0xd2, 0x56, 0x6c, 0x71, 0xf4, 0xcb, 0x01, 0x6f, 0x8e, 0xea, 0x51, 0x61, 0x13, 0x68, 0xad,
	0x0f, 0xcd, 0x9b, 0x5c, 0x9d, 0x19, 0xa9, 0x86, 0x1c, 0x6f, 0x12, 0x5b, 0x8f, 0xbd, 0x86, 0x57,
	0x5d, 0x43, 0x17, 0x9b, 0x3f, 0x08, 0x25, 0x96, 0x32, 0xd3, 0x49, 0x3d, 0x5d, 0xac, 0x25, 0xc8,
	0x53, 0x68, 0x28, 0x9a, 0x16, 0xa1, 0x3f, 0xf4, 0x46, 0x9d, 0x59, 0xb7, 0xfa, 0xfa, 0x3d, 0x4d,
	0x63, 0x23, 0x91, 0xe7, 0x76, 0xcf, 0xa6, 0xd9, 0xf3, 0xb2, 0x32, 0xcd, 0x51, 0x9d, 0x6e, 0x19,
	0x9d, 0x81, 0xff, 0x6e, 0x93, 0xab, 0xfd, 0x58, 0x40, 0xa7, 0xd6, 0x02, 0xb9, 0x06, 0x52, 0x83,
	0x4b, 0xfe, 0x99, 0x8b, 0xaf, 0x3c, 0xf8, 0x8f, 0x5c, 0xc1, 0x45, 0x8d, 0x9f, 0x67, 0x74, 0x8d,
	0x49, 0xe0, 0x90, 0x27, 0x70, 0x59, 0xa3, 0x6f, 0xf3, 0x5c, 0x8a, 0x1d, 0x26, 0x81, 0x4b, 0x42,
	0xe8, 0xd7, 0x84, 0xb7, 0x98, 0xb1, 0x1d, 0x4a, 0x4c, 0x02, 0x6f, 0xbc, 0x82, 0xb6, 0x8d, 0x43,
	0xfa, 0x10, 0x58, 0x50, 0x0d, 0xbb, 0x06, 0x62, 0xd9, 0xdb, 0x1d, 0x65, 0x19, 0x5d, 0x65, 0x18,
	0x38, 0x27, 0xee, 0x39, 0xf2, 0x84, 0xf1, 0x34, 0x70, 0xc9, 0x05, 0x74, 0x2d, 0xbb, 0x10, 0x59,
	0x12, 0x78, 0xb3, 0x18, 0xce, 0xe7, 0x87, 0xdd, 0x17, 0x28, 0x77, 0x6c, 0x8d, 0xe4, 0x0d, 0xb4,
	0xef, 0x24, 0x52, 0x85, 0xfa, 0x7e, 0xdd, 0x93, 0x6a, 0x06, 0xe7, 0x15, 0x34, 0xa5, 0x44, 0xe4,
	0xdb, 0xef, 0x3f, 0xdf, 0xdd, 0xff, 0xa3, 0xb3, 0xe9, 0xee, 0xe5, 0x34, 0x47, 0xf5, 0xda, 0x19,
	0xaf, 0x9a, 0xe6, 0xff, 0xf8, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x8e, 0x91, 0xf0,
	0xc9, 0x03, 0x00, 0x00,
}
