// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.proto

/*
Package gogorpc is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	HeaderMsg
	Value
	RequestMsg
	ReplyMsg
	PublishMsg
	Error
	Result
	ResultValueItems
	ResultValueItem
*/
package gogorpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ClassMethod int32

const (
	ClassMethod_UnknownUnknown ClassMethod = 0
	ClassMethod_DevicePing     ClassMethod = 10
	ClassMethod_DeviceUserData ClassMethod = 11
)

var ClassMethod_name = map[int32]string{
	0:  "UnknownUnknown",
	10: "DevicePing",
	11: "DeviceUserData",
}
var ClassMethod_value = map[string]int32{
	"UnknownUnknown": 0,
	"DevicePing":     10,
	"DeviceUserData": 11,
}

func (x ClassMethod) String() string {
	return proto.EnumName(ClassMethod_name, int32(x))
}
func (ClassMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptorMsg, []int{0} }

type Errno int32

const (
	Errno_Ok        Errno = 0
	Errno_OpNotSupp Errno = 1
)

var Errno_name = map[int32]string{
	0: "Ok",
	1: "OpNotSupp",
}
var Errno_value = map[string]int32{
	"Ok":        0,
	"OpNotSupp": 1,
}

func (x Errno) String() string {
	return proto.EnumName(Errno_name, int32(x))
}
func (Errno) EnumDescriptor() ([]byte, []int) { return fileDescriptorMsg, []int{1} }

type HeaderMsg struct {
	DinetRPC  uint32 `protobuf:"varint,1,opt,name=dinetRPC,proto3" json:"dinetrpc" msg:"dinetrpc"`
	Time      uint64 `protobuf:"varint,2,opt,name=time,proto3" json:"time" msg:"time"`
	DeviceUID string `protobuf:"bytes,3,opt,name=deviceUID,proto3" json:"device:uid,omitempty" msg:"device:uid"`
	UserID    uint32 `protobuf:"varint,4,opt,name=userID,proto3" json:"user:id,omitempty" msg:"user:id"`
	ProjectID uint32 `protobuf:"varint,5,opt,name=projectID,proto3" json:"project:id,omitempty" msg:"project:id"`
}

func (m *HeaderMsg) Reset()                    { *m = HeaderMsg{} }
func (m *HeaderMsg) String() string            { return proto.CompactTextString(m) }
func (*HeaderMsg) ProtoMessage()               {}
func (*HeaderMsg) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{0} }

func (m *HeaderMsg) GetDinetRPC() uint32 {
	if m != nil {
		return m.DinetRPC
	}
	return 0
}

func (m *HeaderMsg) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *HeaderMsg) GetDeviceUID() string {
	if m != nil {
		return m.DeviceUID
	}
	return ""
}

func (m *HeaderMsg) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *HeaderMsg) GetProjectID() uint32 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Bool
	//	*Value_Number
	//	*Value_Str
	Value isValue_Value `protobuf_oneof:"value"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{1} }

type isValue_Value interface {
	isValue_Value()
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,1,opt,name=Bool,proto3,oneof"`
}
type Value_Number struct {
	Number float64 `protobuf:"fixed64,2,opt,name=Number,proto3,oneof"`
}
type Value_Str struct {
	Str string `protobuf:"bytes,3,opt,name=Str,proto3,oneof"`
}

func (*Value_Bool) isValue_Value()   {}
func (*Value_Number) isValue_Value() {}
func (*Value_Str) isValue_Value()    {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetBool() bool {
	if x, ok := m.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Value) GetNumber() float64 {
	if x, ok := m.GetValue().(*Value_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Value) GetStr() string {
	if x, ok := m.GetValue().(*Value_Str); ok {
		return x.Str
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_Bool)(nil),
		(*Value_Number)(nil),
		(*Value_Str)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Bool:
		t := uint64(0)
		if x.Bool {
			t = 1
		}
		_ = b.EncodeVarint(1<<3 | proto.WireVarint)
		_ = b.EncodeVarint(t)
	case *Value_Number:
		_ = b.EncodeVarint(2<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(math.Float64bits(x.Number))
	case *Value_Str:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Str)
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.Bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Bool{x != 0}
		return true, err
	case 2: // value.Number
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Number{math.Float64frombits(x)}
		return true, err
	case 3: // value.Str
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_Str{x}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Bool:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += 1
	case *Value_Number:
		n += proto.SizeVarint(2<<3 | proto.WireFixed64)
		n += 8
	case *Value_Str:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Str)))
		n += len(x.Str)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RequestMsg struct {
	HeaderMsg   `protobuf:"bytes,1,opt,name=Header,embedded=Header" json:""`
	ID          uint32            `protobuf:"varint,2,opt,name=ID,proto3" json:"id" msg:"id"`
	ClassMethod ClassMethod       `protobuf:"varint,3,opt,name=classMethod,proto3,enum=gogorpc.ClassMethod" json:"req" msg:"req"`
	Params      map[string]*Value `protobuf:"bytes,10,rep,name=params" json:"params,omitempty" msg:"params" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestMsg) Reset()                    { *m = RequestMsg{} }
func (m *RequestMsg) String() string            { return proto.CompactTextString(m) }
func (*RequestMsg) ProtoMessage()               {}
func (*RequestMsg) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{2} }

func (m *RequestMsg) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RequestMsg) GetClassMethod() ClassMethod {
	if m != nil {
		return m.ClassMethod
	}
	return ClassMethod_UnknownUnknown
}

func (m *RequestMsg) GetParams() map[string]*Value {
	if m != nil {
		return m.Params
	}
	return nil
}

type ReplyMsg struct {
	HeaderMsg   `protobuf:"bytes,1,opt,name=header,embedded=header" json:""`
	ID          uint32      `protobuf:"varint,2,opt,name=ID,proto3" json:"id" msg:"id"`
	ClassMethod ClassMethod `protobuf:"varint,3,opt,name=classMethod,proto3,enum=gogorpc.ClassMethod" json:"rep" msg:"rep"`
	Error       *Error      `protobuf:"bytes,4,opt,name=error" json:"error,omitempty" msg:"error"`
	Result      *Result     `protobuf:"bytes,5,opt,name=result" json:"result,omitempty" msg:"result"`
}

func (m *ReplyMsg) Reset()                    { *m = ReplyMsg{} }
func (m *ReplyMsg) String() string            { return proto.CompactTextString(m) }
func (*ReplyMsg) ProtoMessage()               {}
func (*ReplyMsg) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{3} }

func (m *ReplyMsg) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ReplyMsg) GetClassMethod() ClassMethod {
	if m != nil {
		return m.ClassMethod
	}
	return ClassMethod_UnknownUnknown
}

func (m *ReplyMsg) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ReplyMsg) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type PublishMsg struct {
	HeaderMsg   `protobuf:"bytes,1,opt,name=Header,embedded=Header" json:""`
	ClassMethod ClassMethod `protobuf:"varint,2,opt,name=classMethod,proto3,enum=gogorpc.ClassMethod" json:"pub" msg:"pub"`
	*Result     `protobuf:"bytes,5,opt,name=result,embedded=result" json:"result,omitempty" msg:"result"`
}

func (m *PublishMsg) Reset()                    { *m = PublishMsg{} }
func (m *PublishMsg) String() string            { return proto.CompactTextString(m) }
func (*PublishMsg) ProtoMessage()               {}
func (*PublishMsg) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{4} }

func (m *PublishMsg) GetClassMethod() ClassMethod {
	if m != nil {
		return m.ClassMethod
	}
	return ClassMethod_UnknownUnknown
}

type Error struct {
	Code  Errno  `protobuf:"varint,1,opt,name=code,proto3,enum=gogorpc.Errno" json:"code"`
	Descr string `protobuf:"bytes,2,opt,name=descr,proto3" json:"descr"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{5} }

func (m *Error) GetCode() Errno {
	if m != nil {
		return m.Code
	}
	return Errno_Ok
}

func (m *Error) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

type Result struct {
	// Types that are valid to be assigned to Result:
	//	*Result_ResultValueItems
	Result isResult_Result `protobuf_oneof:"Result"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{6} }

type isResult_Result interface {
	isResult_Result()
}

type Result_ResultValueItems struct {
	ResultValueItems *ResultValueItems `protobuf:"bytes,1,opt,name=ResultValueItems,oneof"`
}

func (*Result_ResultValueItems) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetResultValueItems() *ResultValueItems {
	if x, ok := m.GetResult().(*Result_ResultValueItems); ok {
		return x.ResultValueItems
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Result) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Result_OneofMarshaler, _Result_OneofUnmarshaler, _Result_OneofSizer, []interface{}{
		(*Result_ResultValueItems)(nil),
	}
}

func _Result_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Result)
	// Result
	switch x := m.Result.(type) {
	case *Result_ResultValueItems:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResultValueItems); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Result.Result has unexpected type %T", x)
	}
	return nil
}

func _Result_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Result)
	switch tag {
	case 1: // Result.ResultValueItems
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResultValueItems)
		err := b.DecodeMessage(msg)
		m.Result = &Result_ResultValueItems{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Result_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Result)
	// Result
	switch x := m.Result.(type) {
	case *Result_ResultValueItems:
		s := proto.Size(x.ResultValueItems)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResultValueItems struct {
	Items []*ResultValueItem `protobuf:"bytes,1,rep,name=Items" json:",omitempty"`
}

func (m *ResultValueItems) Reset()                    { *m = ResultValueItems{} }
func (m *ResultValueItems) String() string            { return proto.CompactTextString(m) }
func (*ResultValueItems) ProtoMessage()               {}
func (*ResultValueItems) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{7} }

func (m *ResultValueItems) GetItems() []*ResultValueItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ResultValueItem struct {
	Uid   uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	Value *Value `protobuf:"bytes,2,opt,name=value" json:"value"`
	Time  uint64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *ResultValueItem) Reset()                    { *m = ResultValueItem{} }
func (m *ResultValueItem) String() string            { return proto.CompactTextString(m) }
func (*ResultValueItem) ProtoMessage()               {}
func (*ResultValueItem) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{8} }

func (m *ResultValueItem) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ResultValueItem) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResultValueItem) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*HeaderMsg)(nil), "gogorpc.HeaderMsg")
	proto.RegisterType((*Value)(nil), "gogorpc.Value")
	proto.RegisterType((*RequestMsg)(nil), "gogorpc.RequestMsg")
	proto.RegisterType((*ReplyMsg)(nil), "gogorpc.ReplyMsg")
	proto.RegisterType((*PublishMsg)(nil), "gogorpc.PublishMsg")
	proto.RegisterType((*Error)(nil), "gogorpc.Error")
	proto.RegisterType((*Result)(nil), "gogorpc.Result")
	proto.RegisterType((*ResultValueItems)(nil), "gogorpc.ResultValueItems")
	proto.RegisterType((*ResultValueItem)(nil), "gogorpc.ResultValueItem")
	proto.RegisterEnum("gogorpc.ClassMethod", ClassMethod_name, ClassMethod_value)
	proto.RegisterEnum("gogorpc.Errno", Errno_name, Errno_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptorMsg) }

var fileDescriptorMsg = []byte{
	// 861 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xa9, 0x1f, 0x8b, 0xc3, 0x58, 0x66, 0x17, 0x46, 0xa1, 0xe4, 0x90, 0x35, 0x16, 0x41,
	0x20, 0x18, 0xae, 0x0c, 0xa8, 0x97, 0x40, 0x87, 0x1c, 0x18, 0x19, 0x90, 0x8a, 0x3a, 0x71, 0x37,
	0x75, 0x7a, 0xea, 0x41, 0x12, 0xb7, 0x12, 0x6b, 0x51, 0xa4, 0x97, 0xa4, 0x0b, 0x3d, 0x40, 0xdf,
	0xad, 0x40, 0x0f, 0xed, 0x13, 0xec, 0xa1, 0x97, 0x02, 0x3c, 0xea, 0x09, 0x8a, 0x9d, 0xa5, 0x25,
	0x59, 0x49, 0x9b, 0x16, 0x45, 0x2e, 0x24, 0xe7, 0xef, 0x9b, 0x99, 0x6f, 0x76, 0x39, 0xe0, 0x44,
	0xe9, 0xac, 0x9b, 0xc8, 0x38, 0x8b, 0xc9, 0xc1, 0x2c, 0x9e, 0xc5, 0x32, 0x99, 0x3e, 0xf9, 0x62,
	0x16, 0x66, 0xf3, 0x7c, 0xd2, 0x9d, 0xc6, 0xd1, 0xb9, 0xd6, 0x9d, 0xa3, 0x7d, 0x92, 0xff, 0x80,
	0x12, 0x0a, 0xf8, 0x65, 0xe2, 0xd8, 0xaf, 0x36, 0x38, 0x43, 0x31, 0x0e, 0x84, 0xbc, 0x4c, 0x67,
	0xa4, 0x0f, 0xcd, 0x20, 0x5c, 0x8a, 0x8c, 0x5f, 0xbd, 0x6a, 0x5b, 0x27, 0x56, 0xe7, 0xd0, 0x7f,
	0x5a, 0x28, 0x6a, 0x74, 0x32, 0x99, 0xae, 0x15, 0x6d, 0x45, 0xe9, 0xac, 0xcf, 0xee, 0x15, 0x8c,
	0x6f, 0xfc, 0xc9, 0x29, 0xd4, 0xb2, 0x30, 0x12, 0x6d, 0xfb, 0xc4, 0xea, 0xd4, 0xfc, 0xcf, 0x0b,
	0x45, 0x51, 0x5e, 0x2b, 0x0a, 0x18, 0xa3, 0x05, 0xc6, 0x51, 0x47, 0xbe, 0x02, 0x27, 0x10, 0x77,
	0xe1, 0x54, 0x5c, 0x8f, 0x06, 0xed, 0xea, 0x89, 0xd5, 0x71, 0xfc, 0xb3, 0x42, 0xd1, 0x63, 0xa3,
	0xec, 0xe7, 0x61, 0x70, 0x16, 0x47, 0x61, 0x26, 0xa2, 0x24, 0x5b, 0xad, 0x15, 0xf5, 0x4c, 0xd2,
	0x8d, 0x91, 0xf1, 0x6d, 0x38, 0x79, 0x09, 0x8d, 0x3c, 0x15, 0x72, 0x34, 0x68, 0xd7, 0xb0, 0xe2,
	0xe7, 0x85, 0xa2, 0x9f, 0x69, 0x4d, 0x7f, 0x0f, 0xe5, 0x10, 0x51, 0x4a, 0x0b, 0xe3, 0x65, 0x94,
	0xae, 0x25, 0x91, 0xf1, 0x8f, 0x62, 0x9a, 0x8d, 0x06, 0xed, 0x3a, 0x42, 0x60, 0x2d, 0xa5, 0xb2,
	0xff, 0xc1, 0x5a, 0xb6, 0x46, 0xc6, 0xb7, 0xe1, 0xec, 0x5b, 0xa8, 0xbf, 0x1b, 0x2f, 0x72, 0x41,
	0x8e, 0xa1, 0xe6, 0xc7, 0xf1, 0x02, 0x49, 0x6c, 0x0e, 0x2b, 0x1c, 0x25, 0xd2, 0x86, 0xc6, 0xeb,
	0x3c, 0x9a, 0x08, 0x89, 0x24, 0x59, 0xc3, 0x0a, 0x2f, 0x65, 0x42, 0xa0, 0xfa, 0x36, 0x93, 0x86,
	0x8a, 0x61, 0x85, 0x6b, 0xc1, 0x3f, 0x80, 0xfa, 0x9d, 0x06, 0x63, 0x7f, 0xd8, 0x00, 0x5c, 0xdc,
	0xe6, 0x22, 0xcd, 0xf4, 0x90, 0x5e, 0x40, 0xc3, 0x4c, 0x0c, 0xd1, 0xdd, 0x1e, 0xe9, 0x96, 0xb3,
	0xef, 0x6e, 0x06, 0xe9, 0x3f, 0xfa, 0x45, 0xd1, 0xca, 0xef, 0x8a, 0x5a, 0x85, 0xa2, 0x15, 0x5e,
	0xfa, 0x13, 0x06, 0xf6, 0x68, 0x80, 0xb9, 0x0f, 0x7d, 0x52, 0x28, 0x6a, 0x87, 0xc1, 0x5a, 0xd1,
	0x26, 0x76, 0xa4, 0x3b, 0xb1, 0x47, 0x03, 0xf2, 0x35, 0xb8, 0xd3, 0xc5, 0x38, 0x4d, 0x2f, 0x45,
	0x36, 0x8f, 0x03, 0xac, 0xa8, 0xd5, 0x3b, 0xde, 0xa4, 0x78, 0xb5, 0xb5, 0xf9, 0xc7, 0x85, 0xa2,
	0x55, 0x29, 0x6e, 0xd7, 0x8a, 0x3a, 0x88, 0x21, 0xc5, 0x2d, 0xe3, 0xbb, 0xe1, 0xe4, 0x7b, 0x68,
	0x24, 0x63, 0x39, 0x8e, 0xd2, 0x36, 0x9c, 0x54, 0x3b, 0x6e, 0x8f, 0x6e, 0x80, 0xb6, 0x0d, 0x75,
	0xaf, 0xd0, 0xe3, 0x62, 0x99, 0xc9, 0x95, 0xff, 0xac, 0x50, 0xd4, 0x33, 0x21, 0x0f, 0x68, 0x7f,
	0x64, 0x68, 0x47, 0x03, 0xe3, 0x25, 0xe8, 0x93, 0x11, 0xb8, 0x3b, 0xc1, 0xc4, 0x83, 0xea, 0x8d,
	0x58, 0x21, 0x2d, 0x0e, 0xd7, 0x9f, 0xe4, 0x59, 0xc9, 0x21, 0x36, 0xed, 0xf6, 0x5a, 0x9b, 0xf4,
	0x38, 0x26, 0x6e, 0x8c, 0x7d, 0xfb, 0x85, 0xc5, 0x7e, 0xb3, 0xa1, 0xc9, 0x45, 0xb2, 0x58, 0x95,
	0x14, 0xcf, 0xff, 0x23, 0xc5, 0xf3, 0x4f, 0x49, 0x71, 0xb2, 0x43, 0x71, 0xb2, 0x47, 0xf1, 0x10,
	0xea, 0x42, 0xca, 0x58, 0xe2, 0xf1, 0xdf, 0x6d, 0xf1, 0x42, 0x6b, 0x7d, 0x56, 0x28, 0x7a, 0x84,
	0x0e, 0x0f, 0xf8, 0x74, 0x11, 0x0d, 0xf5, 0x8c, 0x1b, 0x00, 0x72, 0x09, 0x0d, 0x29, 0xd2, 0x7c,
	0x91, 0xe1, 0x35, 0x70, 0x7b, 0x47, 0x3b, 0xc3, 0xd2, 0x6a, 0x33, 0x1c, 0xe3, 0xf2, 0x81, 0xe1,
	0x18, 0x03, 0xe3, 0x25, 0x08, 0xfb, 0xd3, 0x02, 0xb8, 0xca, 0x27, 0x8b, 0x30, 0x9d, 0xff, 0xbf,
	0x63, 0xbb, 0xc7, 0x97, 0xfd, 0x31, 0xbe, 0x92, 0x7c, 0xb2, 0xe1, 0x2b, 0xc9, 0x27, 0x7b, 0x7c,
	0x7d, 0xf3, 0xb1, 0x2e, 0x3b, 0x65, 0x01, 0xff, 0xbe, 0xd3, 0x77, 0x50, 0x47, 0xb2, 0xc9, 0x19,
	0xd4, 0xa6, 0x71, 0x20, 0xb0, 0xc3, 0xd6, 0xc3, 0x51, 0x2c, 0x63, 0xbf, 0xa9, 0xff, 0x89, 0xda,
	0xce, 0xf1, 0x49, 0x28, 0xd4, 0x03, 0x91, 0x4e, 0xcd, 0xdf, 0xc0, 0xf1, 0x9d, 0x42, 0x51, 0xa3,
	0xe0, 0xe6, 0xc5, 0x6e, 0xa0, 0x61, 0x6a, 0x22, 0xdf, 0x81, 0x67, 0xbe, 0xf0, 0xdc, 0x8e, 0x32,
	0x11, 0xa5, 0x25, 0x8d, 0x8f, 0xf7, 0xca, 0xdf, 0x3a, 0xf8, 0xad, 0x42, 0x51, 0xd8, 0x96, 0x3f,
	0xac, 0xf0, 0xf7, 0x40, 0xfc, 0xe6, 0x7d, 0x0a, 0xc6, 0xdf, 0x4f, 0x41, 0x5e, 0x42, 0xfd, 0x3e,
	0x97, 0xbe, 0xbd, 0xed, 0xbf, 0xcb, 0xb5, 0x9f, 0x8a, 0x9b, 0x30, 0xf6, 0xb3, 0x05, 0x47, 0x7b,
	0xae, 0xe4, 0x31, 0x54, 0xf3, 0x30, 0x28, 0xd7, 0xcb, 0x81, 0x9e, 0x57, 0x1e, 0x06, 0x5c, 0x3f,
	0xc8, 0xf9, 0x3f, 0xde, 0x56, 0x43, 0xd0, 0xdd, 0xce, 0xc5, 0x25, 0xcf, 0xcb, 0x9d, 0x53, 0xc5,
	0x9d, 0xa3, 0xef, 0x5b, 0x4b, 0xcb, 0x3b, 0x85, 0xa0, 0xfd, 0xf4, 0x02, 0xdc, 0x9d, 0x53, 0x42,
	0x08, 0xb4, 0xae, 0x97, 0x37, 0xcb, 0xf8, 0xa7, 0x65, 0xf9, 0xf2, 0x2a, 0xa4, 0x05, 0x30, 0xc0,
	0x9d, 0x72, 0x15, 0x2e, 0x67, 0x1e, 0x68, 0x1f, 0x23, 0x5f, 0xa7, 0x42, 0x0e, 0xc6, 0xd9, 0xd8,
	0x73, 0x4f, 0x9f, 0xe2, 0x9c, 0x97, 0x31, 0x69, 0x80, 0xfd, 0xe6, 0xc6, 0xab, 0x90, 0x43, 0x70,
	0xde, 0x24, 0xaf, 0xe3, 0xec, 0x6d, 0x9e, 0x24, 0x9e, 0x35, 0x69, 0xe0, 0x4e, 0xfd, 0xf2, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xe3, 0xb7, 0x10, 0x98, 0x07, 0x00, 0x00,
}
